name: CI

on:
  push:
    branches: [ main, feat/*, copilot/* ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm install
    
    - name: Install server dependencies
      run: |
        cd server
        npm install
    
    - name: Lint and build server
      run: |
        cd server
        npm run lint
        npm run build
    
    - name: Install client dependencies
      run: |
        cd client
        npm install
    
    - name: Lint and build client
      run: |
        cd client
        npm run lint
        npm run build
    
    - name: Build summary
      run: |
        echo "✅ Server and client built successfully"
        echo "📦 Ready for deployment"
